### ISSUE TITLE
Compilation error: size of array ‘dummy’ is negative , file: dwarf.c

### ISSUE THREAD

**Issue by bingosxs** [codespecs/fjalar#16] opened 2016-04-19 01:58 UTC
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../VEX/pub -I../VEX/pub -DVGA_x86=1 -DVGO_linux=1 -DVGP_x86_linux=1 -DVGPV_x86_linux_vanilla=1  -m32 -mpreferred-stack-boundary=2 -O2 -g -std=gnu99 -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wold-style-declaration -fno-stack-protector -fno-strict-aliasing -fno-builtin -fomit-frame-pointer -Iinclude -I../VEX/pub -I../include -I.. -O0 -Wno-cast-qual -MT fjalar_x86_linux-dwarf.o -MD -MP -MF .deps/fjalar_x86_linux-dwarf.Tpo -c -o fjalar_x86_linux-dwarf.o `test -f 'dwarf.c' || echo './'`dwarf.c
dwarf.c: In function ‘read_and_display_attr_value’:
dwarf.c:1983:10: warning: left shift count >= width of type [enabled by default]
          harvest_ordinary_unsigned_value(entry, attribute, (high_bits << 32) | utmp);
          ^
dwarf.c:501:11: error: size of array ‘dummy’ is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \
           ^
dwarf.c:1992:6: note: in expansion of macro ‘SAFE_BYTE_GET’
      SAFE_BYTE_GET (uvalue, data, 8, end);
      ^
dwarf.c: In function ‘process_debug_info’:
dwarf.c:501:11: error: size of array ‘dummy’ is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \
           ^
dwarf.c:2658:8: note: in expansion of macro ‘SAFE_BYTE_GET’
        SAFE_BYTE_GET (length, section_begin + 4, 8, end);
        ^
dwarf.c:501:11: error: size of array ‘dummy’ is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \
           ^
dwarf.c:520:7: note: in expansion of macro ‘SAFE_BYTE_GET’
       SAFE_BYTE_GET (VAL, PTR, AMOUNT, END);  \
       ^
# 

gcc version:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

**Comment by markro49** [comment] 2016-04-19 03:17
As noted in the CHANGES file, we no longer support 32 bit hosts for Fjalar.

**Comment by bingosxs** [comment] 2016-04-19 05:52
similar errors in rhel6_x86_64.
```
Linux DL380 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 08:24:23 CST 2015 x86_64 x86_64 x86_64 GNU/Linux
[canicula@DL380 fjalar]$ cat /etc/issue
Scientific Linux release 6.1 (Carbon)
Kernel \r on an \m

[canicula@DL380 fjalar]$ gcc -v
 specs。
：x86_64-redhat-linux
：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
：posix
gcc  4.4.5 20110214 (Red Hat 4.4.5-6) (GCC) 

```
The error information:
```
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../VEX/pub -I../VEX/pub -DVGA_x86=1 -DVGO_linux=1 -DVGP_x86_linux=1 -DVGPV_x86_linux_vanilla=1  -m32 -mpreferred-stack-boundary=2 -O2 -g -std=gnu99 -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wold-style-declaration -fno-stack-protector -fno-strict-aliasing -fno-builtin -fomit-frame-pointer -Iinclude -I../VEX/pub -I../include -I.. -O0 -Wno-cast-qual -MT fjalar_x86_linux-dwarf.o -MD -MP -MF .deps/fjalar_x86_linux-dwarf.Tpo -c -o fjalar_x86_linux-dwarf.o `test -f 'dwarf.c' || echo './'`dwarf.c
dwarf.c: In function 'read_and_display_attr_value':
dwarf.c:1983: warning: left shift count >= width of type
dwarf.c:1992: error: size of array 'dummy' is negative
dwarf.c: In function 'process_debug_info':
dwarf.c:2658: error: size of array 'dummy' is negative
dwarf.c:2749: error: size of array 'dummy' is negative
dwarf.c: In function 'read_debug_line_header':
dwarf.c:3212: error: size of array 'dummy' is negative
dwarf.c: In function 'display_debug_pubnames_worker':
dwarf.c:4374: error: size of array 'dummy' is negative
dwarf.c: In function 'display_debug_aranges':
dwarf.c:5601: error: size of array 'dummy' is negative
dwarf.c: In function 'display_debug_frames':
dwarf.c:6471: error: size of array 'dummy' is negative
dwarf.c:6594: error: size of array 'dummy' is negative
dwarf.c:7339: error: size of array 'dummy' is negative

```

**Comment by markro49** [comment] 2016-04-19 16:20
Could you please provide exact version of Linux you are using?  I saw Ubuntu 14.04.4 in one of your other posts - but perhaps that was for 32 bits.  With 64 bits you are using Scientific Linux?  I'm not familiar with that one.

**Comment by bingosxs** [comment] 2016-04-20 01:58
The 64bits system is Scientific Linux, a community distribution of Red Hat Enterprise Linux(RHEL).
Another famous community distribution is CENTOS.
They are almost binary-compatible.

I dig the Makefile and found that the Makefile is not correctly generated.
```
fjalar_x86_linux-fjalar_dwarf.o: fjalar_dwarf.c
        $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(fjalar_x86_linux_CPPFLAGS) $(CPPFLAGS) $(fjalar_x86_linux_CFLAGS) $(CFLAGS) -MT fjalar_x86_linux-fjalar_dwarf.o -MD -MP -MF $(DEPDIR)/fjalar_x86_linux-fjalar_dwarf.Tpo -c -o fjalar_x86_linux-fjalar_dwarf.o `test -f 'fjalar_dwarf.c' || echo '$(srcdir)/'`fjalar_dwarf.c
        $(am__mv) $(DEPDIR)/fjalar_x86_linux-fjalar_dwarf.Tpo $(DEPDIR)/fjalar_x86_linux-fjalar_dwarf.Po
```
` $(fjalar_x86_linux_CPPFLAGS)`  **should be** `$(fjalar_amd64_linux_CFLAGS)`.

I have no idea about a fix.
Can you help me ?

**Comment by bingosxs** [comment] 2016-04-20 02:05
I upload the valgrind/fjalar/Makefile
[makefile.zip](https://github.com/codespecs/fjalar/files/227125/makefile.zip)

**Comment by markro49** [comment] 2016-04-20 13:14
I will look into creating a virtual machine with Scientific Linux for testing - but in the mean time, could you rerun the "./configure" fjalar build step and attach a copy of the log.  Thank you

**Comment by markro49** [comment] 2016-04-21 15:42
I was not able to install 6.1 due to a bug in the install.  I was able to install 6.2 and everything worked fine.  6.1 is dated July 2011 - the latest version is 6.7 dated Aug 2015.  I think you should consider upgrading your system.

**Comment by bingosxs** [comment] 2016-04-22 08:10
Thanks for your work.
I upload the Valgrind/config.log file.
[config.log.zip](https://github.com/codespecs/fjalar/files/231367/config.log.zip)

I can create a virtual machine to install  newer OS.
However the base server is not likely to be upgraded --- it is a production system.

**Comment by markro49** [comment] 2016-04-22 22:04
I looked at config.log and it confirms your software is quite old.  However, I didn't see anything obviously wrong in the log.  I'm afraid building a virtual machine is still your best bet.

**Comment by mernst** [comment] 2016-04-22 22:43
Another alternative would be for you to implement 32-bit support in Fjalar. We recently disabled it because we don't have the resources to continue maintaining Fjalar for 32-bit architectures ourselves in the absence of external help or funding.

I'm going to close this issue now that we understand the issues, but thanks for letting us know about the problem and let us know if you encounter problems on a 64-bit OS.

**Comment by jixiaonanzhuaizhuai** [comment] 2017-03-31 01:32
dwarf.c: In function 'read_and_display_attr_value':
dwarf.c:1983:10: warning: left shift count >= width of type [enabled by default]
          harvest_ordinary_unsigned_value(entry, attribute, (high_bits << 32) | utmp);
          ^
dwarf.c:501:11: error: size of array 'dummy' is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \
           ^
dwarf.c:1992:6: note: in expansion of macro 'SAFE_BYTE_GET'
      SAFE_BYTE_GET (uvalue, data, 8, end);
      ^
dwarf.c: In function 'process_debug_info':
dwarf.c:501:11: error: size of array 'dummy' is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \
           ^
dwarf.c:2662:8: note: in expansion of macro 'SAFE_BYTE_GET'
        SAFE_BYTE_GET (length, section_begin + 4, 8, end);
        ^
dwarf.c:501:11: error: size of array 'dummy' is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \
           ^
dwarf.c:520:7: note: in expansion of macro 'SAFE_BYTE_GET'
       SAFE_BYTE_GET (VAL, PTR, AMOUNT, END);  \
       ^
dwarf.c:2753:4: note: in expansion of macro 'SAFE_BYTE_GET_AND_INC'
    SAFE_BYTE_GET_AND_INC (compunit.cu_length, hdrptr, 8, end);
    ^
dwarf.c: In function 'read_debug_line_header':
dwarf.c:501:11: error: size of array 'dummy' is negative
       int dummy [sizeof (VAL) < (AMOUNT) ? -1 : 1] ATTRIBUTE_UNUSED ; \




root@ubuntu:~# uname -a
Linux ubuntu 3.16.0-51-generic #69~14.04.1-Ubuntu SMP Wed Oct 7 15:32:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


I am 64-bit system, why is there such a mistake, can give me an idea？

**Comment by markro49** [comment] 2017-04-04 15:58
I’m sorry you are having trouble building Fjalar; however, you did not supply enough information to diagnose the problem.  Please report it in detail, using the instructions in section "reporting problems" of the manual:
https://plse.cs.washington.edu/daikon/download/doc/daikon.html
 
In particular, what version of Daikon?; did you clone the repo or download the tar file?; and a complete list of the commands and their output you used to reach this point.
 
Thank you,
Mark Roberts

**Comment by mernst** [comment] 2017-05-22 15:52
I'm closing this because no reproducible test case has been given.
We can reopen it if someone provides a way to reproduce the issue.

**Closed by mernst** 2017-05-22 15:52 UTC
